version: '3.8'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: henrique123
      MYSQL_DATABASE: payments
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
